// backend/seed-data.js

const sampleProperties = [
  {
    title: "Luxury Villa - Palm Jumeirah",
    location: "Palm Jumeirah, Dubai",
    price: 2500000,
    bedrooms: 4,
    bathrooms: 5,
    size: 4500,
    status: "For Sale",
    propertyType: "Villa",
    description: "Luxury villa with sea view and private pool.",
    mainImage: "assets/img/card_img_1.jpg",
    roi: 8, payment_plan: 7, delivery: 6, urgency: 8,
    prestige: 9, amenities: 8, velocity: 7, launch: 6,
    price_per_sqm: 7, horizon: 8, type_fit: 7, legal: 8,
    lat: 25.112, lng: 55.139
  },
  {
    title: "Modern Apartment - Downtown",
    location: "Downtown Dubai",
    price: 1200000,
    bedrooms: 2,
    bathrooms: 2,
    size: 1200,
    status: "For Rent",
    propertyType: "Apartment",
    description: "Modern apartment in the city center.",
    mainImage: "assets/img/card_img_2.jpg",
    roi: 6, payment_plan: 5, delivery: 7, urgency: 5,
    prestige: 6, amenities: 7, velocity: 6, launch: 5,
    price_per_sqm: 6, horizon: 5, type_fit: 6, legal: 7,
    lat: 25.1972, lng: 55.2744
  },
  {
    title: "Family House - Jumeirah Village",
    location: "Jumeirah Village Circle",
    price: 1750000,
    bedrooms: 3,
    bathrooms: 3,
    size: 2200,
    status: "For Sale",
    propertyType: "House",
    description: "Spacious family house with garden.",
    mainImage: "assets/img/card_img_3.jpg",
    roi: 7, payment_plan: 6, delivery: 7, urgency: 6,
    prestige: 6, amenities: 7, velocity: 6, launch: 5,
    price_per_sqm: 6, horizon: 6, type_fit: 6, legal: 6,
    lat: 25.055, lng: 55.209
  },
  {
    title: "Luxury Condo - Dubai Marina",
    location: "Dubai Marina",
    price: 2000000,
    bedrooms: 3,
    bathrooms: 4,
    size: 2800,
    status: "For Sale",
    propertyType: "Condo",
    description: "Luxury condo with sea view in Dubai Marina.",
    mainImage: "assets/img/card_img_4.jpg",
    roi: 8, payment_plan: 7, delivery: 6, urgency: 7,
    prestige: 8, amenities: 8, velocity: 7, launch: 6,
    price_per_sqm: 7, horizon: 7, type_fit: 7, legal: 8,
    lat: 25.080, lng: 55.140
  },
  {
    title: "Townhouse - Arabian Ranches",
    location: "Arabian Ranches",
    price: 1600000,
    bedrooms: 3,
    bathrooms: 3,
    size: 2100,
    status: "For Sale",
    propertyType: "Townhouse",
    description: "Modern townhouse in Arabian Ranches.",
    mainImage: "assets/img/card_img_5.jpg",
    roi: 7, payment_plan: 6, delivery: 6, urgency: 6,
    prestige: 7, amenities: 7, velocity: 6, launch: 5,
    price_per_sqm: 6, horizon: 6, type_fit: 7, legal: 7,
    lat: 25.030, lng: 55.255
  },
  {
    title: "Cozy Apartment - Business Bay",
    location: "Business Bay",
    price: 950000,
    bedrooms: 1,
    bathrooms: 1,
    size: 800,
    status: "For Rent",
    propertyType: "Apartment",
    description: "Cozy studio apartment with city view.",
    mainImage: "assets/img/card_img_6.jpg",
    roi: 5, payment_plan: 5, delivery: 6, urgency: 5,
    prestige: 6, amenities: 6, velocity: 6, launch: 5,
    price_per_sqm: 5, horizon: 5, type_fit: 5, legal: 6,
    lat: 25.185, lng: 55.273
  },
  {
    title: "Penthouse - Downtown Dubai",
    location: "Downtown Dubai",
    price: 4500000,
    bedrooms: 5,
    bathrooms: 6,
    size: 5000,
    status: "For Sale",
    propertyType: "Apartment",
    description: "Luxury penthouse with Burj Khalifa view.",
    mainImage: "assets/img/card_img_7.jpg",
    roi: 9, payment_plan: 8, delivery: 7, urgency: 8,
    prestige: 10, amenities: 9, velocity: 8, launch: 7,
    price_per_sqm: 8, horizon: 8, type_fit: 9, legal: 9,
    lat: 25.1975, lng: 55.2743
  },
  {
    title: "Beachfront Villa - JBR",
    location: "Jumeirah Beach Residence",
    price: 3800000,
    bedrooms: 4,
    bathrooms: 5,
    size: 4200,
    status: "For Sale",
    propertyType: "Villa",
    description: "Beachfront villa with private beach access.",
    mainImage: "assets/img/card_img_8.jpg",
    roi: 8, payment_plan: 7, delivery: 7, urgency: 7,
    prestige: 9, amenities: 9, velocity: 7, launch: 6,
    price_per_sqm: 8, horizon: 7, type_fit: 8, legal: 8,
    lat: 25.080, lng: 55.133
  },
  {
    title: "Smart Apartment - Al Barsha",
    location: "Al Barsha",
    price: 1100000,
    bedrooms: 2,
    bathrooms: 2,
    size: 1300,
    status: "For Sale",
    propertyType: "Apartment",
    description: "Modern apartment with smart home system.",
    mainImage: "assets/img/card_img_9.jpg",
    roi: 6, payment_plan: 6, delivery: 7, urgency: 6,
    prestige: 6, amenities: 7, velocity: 6, launch: 6,
    price_per_sqm: 6, horizon: 6, type_fit: 6, legal: 6,
    lat: 25.110, lng: 55.212
  },
  {
    title: "Luxury House - Emirates Hills",
    location: "Emirates Hills",
    price: 5500000,
    bedrooms: 6,
    bathrooms: 7,
    size: 6500,
    status: "For Sale",
    propertyType: "House",
    description: "Ultra luxury house with swimming pool.",
    mainImage: "assets/img/card_img_10.jpg",
    roi: 9, payment_plan: 8, delivery: 7, urgency: 9,
    prestige: 10, amenities: 9, velocity: 8, launch: 8,
    price_per_sqm: 9, horizon: 9, type_fit: 9, legal: 9,
    lat: 25.083, lng: 55.173
  },
  {
    title: "Modern Condo - Dubai Creek",
    location: "Dubai Creek Harbour",
    price: 1800000,
    bedrooms: 3,
    bathrooms: 3,
    size: 2000,
    status: "For Sale",
    propertyType: "Condo",
    description: "Modern condo with elegant architecture.",
    mainImage: "assets/img/card_img_11.jpg",
    roi: 7, payment_plan: 6, delivery: 6, urgency: 6,
    prestige: 7, amenities: 7, velocity: 6, launch: 6,
    price_per_sqm: 7, horizon: 7, type_fit: 7, legal: 7,
    lat: 25.200, lng: 55.340
  },
  {
    title: "Townhouse - Mirdif",
    location: "Mirdif",
    price: 1400000,
    bedrooms: 3,
    bathrooms: 3,
    size: 1900,
    status: "For Sale",
    propertyType: "Townhouse",
    description: "Townhouse suitable for family living.",
    mainImage: "assets/img/card_img_12.jpg",
    roi: 6, payment_plan: 6, delivery: 6, urgency: 6,
    prestige: 6, amenities: 6, velocity: 6, launch: 6,
    price_per_sqm: 6, horizon: 6, type_fit: 6, legal: 6,
    lat: 25.215, lng: 55.415
  },
  {
    title: "Apartment - Dubai Silicon Oasis",
    location: "Dubai Silicon Oasis",
    price: 900000,
    bedrooms: 1,
    bathrooms: 1,
    size: 750,
    status: "For Rent",
    propertyType: "Apartment",
    description: "Affordable apartment in Silicon Oasis.",
    mainImage: "assets/img/card_img_13.jpg",
    roi: 5, payment_plan: 5, delivery: 6, urgency: 5,
    prestige: 5, amenities: 5, velocity: 5, launch: 5,
    price_per_sqm: 5, horizon: 5, type_fit: 5, legal: 5,
    lat: 25.126, lng: 55.387
  },
  {
    title: "Villa - The Springs",
    location: "The Springs",
    price: 2200000,
    bedrooms: 4,
    bathrooms: 4,
    size: 3000,
    status: "For Sale",
    propertyType: "Villa",
    description: "Villa surrounded by nature in The Springs.",
    mainImage: "assets/img/card_img_14.jpg",
    roi: 7, payment_plan: 6, delivery: 7, urgency: 7,
    prestige: 7, amenities: 7, velocity: 7, launch: 6,
    price_per_sqm: 7, horizon: 7, type_fit: 7, legal: 7,
    lat: 25.065, lng: 55.223
  },
  {
    title: "Condo - DIFC",
    location: "Dubai International Financial Centre",
    price: 1950000,
    bedrooms: 2,
    bathrooms: 2,
    size: 1500,
    status: "For Sale",
    propertyType: "Condo",
    description: "Modern condo close to financial district.",
    mainImage: "assets/img/card_img_15.jpg",
    roi: 7, payment_plan: 6, delivery: 6, urgency: 6,
    prestige: 7, amenities: 7, velocity: 6, launch: 6,
    price_per_sqm: 7, horizon: 7, type_fit: 7, legal: 7,
    lat: 25.210, lng: 55.280
  },
  {
    title: "Modern Apartment - Downtown",
    location: "Downtown Dubai",
    price: 1200000,
    bedrooms: 2,
    bathrooms: 2,
    size: 1200,
    status: "Off-Plan",
    propertyType: "Apartment",
    description: "Modern apartment in the city center.",
    mainImage: "assets/img/card_img_2.jpg",
    roi: 6, payment_plan: 5, delivery: 7, urgency: 5,
    prestige: 6, amenities: 7, velocity: 6, launch: 5,
    price_per_sqm: 6, horizon: 5, type_fit: 6, legal: 7,
    lat: 25.1972, lng: 55.2744
  },
  {
    title: "Family House - Jumeirah Village",
    location: "Jumeirah Village Circle",
    price: 1800000,
    bedrooms: 3,
    bathrooms: 3,
    size: 2000,
    status: "Off-Plan",
    propertyType: "House",
    description: "Spacious family home in JVC.",
    mainImage: "assets/img/card_img_3.jpg",
    roi: 7, payment_plan: 6, delivery: 8, urgency: 6,
    prestige: 7, amenities: 6, velocity: 7, launch: 6,
    price_per_sqm: 7, horizon: 6, type_fit: 7, legal: 8,
    lat: 25.0607, lng: 55.2044
  },
  {
    title: "Palm Horizon Villa",
    location: "Palm Jumeirah",
    price: 4200000,
    bedrooms: 4,
    bathrooms: 5,
    size: 3200,
    status: "Off-Plan",
    propertyType: "Villa",
    description: "Exclusive Off-Plan villas with private pools.",
    mainImage: "assets/img/card_img_4.jpg",
    roi: 8, payment_plan: 6, delivery: 7, urgency: 5,
    prestige: 9, amenities: 8, velocity: 6, launch: 6,
    price_per_sqm: 8, horizon: 7, type_fit: 8, legal: 9,
    lat: 25.112, lng: 55.139
  },
  {
    title: "Skyline Tower",
    location: "Business Bay",
    price: 2000000,
    bedrooms: 2,
    bathrooms: 3,
    size: 1600,
    status: "Ready",
    propertyType: "Apartment",
    description: "High-rise apartments with Burj Khalifa view.",
    mainImage: "assets/img/card_img_5.jpg",
    roi: 7, payment_plan: 5, delivery: 8, urgency: 6,
    prestige: 7, amenities: 8, velocity: 6, launch: 7,
    price_per_sqm: 7, horizon: 7, type_fit: 6, legal: 7,
    lat: 25.185, lng: 55.272
  },
  {
    title: "Green Park Townhouse",
    location: "Mirdif",
    price: 1700000,
    bedrooms: 3,
    bathrooms: 3,
    size: 2000,
    status: "Ready",
    propertyType: "Townhouse",
    description: "Family-friendly Ready townhouses with gardens.",
    mainImage: "assets/img/card_img_6.jpg",
    roi: 6, payment_plan: 4, delivery: 7, urgency: 5,
    prestige: 6, amenities: 6, velocity: 5, launch: 5,
    price_per_sqm: 6, horizon: 6, type_fit: 6, legal: 7,
    lat: 25.218, lng: 55.319
  }

];

// ✅ Export
module.exports = sampleProperties;
